### ISSUE TITLE
Pipes do not working

### ISSUE THREAD

**Issue by phts** [dnschneid/xfce4-genmon-plugin#1]
For example:

    cat /home/user/some_file | cut -c-5

Produces:

    cat: invalid option -- 'c'
    Try 'cat --help' for more information

But it works in terminal.
Is there any possible fixes or workarounds for it?

Also I tried these commands which do not work as well in genmon:

    echo `cat /home/user/some_file | cut -c-5`

prints `cat /home/user/some_file | cut -c-5`

    $(cat /home/user/some_file | cut -c-5)

prints `$(cat: No such file or directory`

**Comment by phts** [comment]
Found solution :)

Use: `/bin/bash -c 'cat /home/user/some_file | cut -c-5'`

**Comment by dnschneid** [comment]
sh is generally a better choice than bash; it's much lighter weight.

In your case though, you don't need either, since the pipe is unnecessary:
`cut -c-5 /home/user/some_file`
